main: games.aternos.odessa.example.hungergames.HungerGames
name: OdessaExampleHG
version: 1
description: Hunger Games Example Game
authors: [_Bot_, AternosGamesContributors] # If you make a pull request (and contribute something) add your name :)
depend: [OdessaGameApi]
website: aternos.games
api-version: 1.14